### ISSUE TITLE
errors  like The blank final field uid may not have been initialized

### ISSUE THREAD

**Issue by nakirekantisaikumar** [mzheravin/exchange-core#10]
I downloaded the zip file.. and I imported to downloaded project into STS 4 and I am getting too many errors in java files.

Errors Like :
The blank final field uid may not have been initialized

and there are undefined methods are being called.

I have cleaned the project and I refreshed the project. still, I am getting many errors.

Could you please tell me why I am getting these errors..
And I could you please what is java version. And in which IDE u wrote the code.

**Comment by mzheravin** [comment]
Hello,
Java version is 8
I use IntelliJ Idea IDE.
You have to install Lombok plugin - because lot of trivial boilerplate code (like setter, getters, etc) is actually hidden. So plain IDE will always complain about syntax.
In the future I will remove Lombok.
