### ISSUE TITLE
I need your help

### ISSUE THREAD

**Issue by vahidalvandi** [mzheravin/exchange-core#115]
Hello, thank you for publishing this project
I have been researching digital currency exchange for some time and I really do not know where to start. I am more interested in working with Python and need guidance on what the database structure and data type should look like. Thanks for taking the time to guide me.

**Comment by mzheravin** [comment]
Dear @vahidalvandi ,
You can ask for hep in the Telegram group https://t.me/exchangecoretalks

**Comment by vahidalvandi** [comment]
I asked my questions but I think it would be better if you answer.
Does this project have a stop loss?
And can I run this project in a real digital currency exchange?
