### ISSUE TITLE
Does exchange-core support java17 or higher version

### ISSUE THREAD

**Issue by shanhashcah** [mzheravin/exchange-core#138]
As java is coming up with higher version like java 17 or we can say now java 19. So we want to run exchange-core with java 17 then what are the changes we need to do? Please guide us.

Thanks

**Comment by esanchezros** [comment]
You can run exchange-core with Java 17 providing these JVM parameters:

```
--add-exports=java.base/jdk.internal.ref=ALL-UNNAMED
--add-exports=java.base/sun.nio.ch=ALL-UNNAMED
--add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED
--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED
--add-opens=jdk.compiler/com.sun.tools.javac=ALL-UNNAMED
--add-opens=java.base/java.lang=ALL-UNNAMED
--add-opens=java.base/java.lang.reflect=ALL-UNNAMED
--add-opens=java.base/java.io=ALL-UNNAMED
--add-opens=java.base/java.util=ALL-UNNAMED
```

**Comment by shanhashcah** [comment]
@esanchezros Thanks but I have below doubt

I have added these VM parameters in mu eclipse configuration settings file but I am getting below error

Type java.lang.String is indirectly referenced from required .class files but cannot be resolved since the declaring package java.lang exported from module java.base conflicts with a package accessible from module <unnamed>

Please guide me.

Thanks

**Comment by esanchezros** [comment]
I have configured my maven-compiler-plugin like this:

```
	<plugin>
		<groupId>org.apache.maven.plugins</groupId>
		<artifactId>maven-compiler-plugin</artifactId>
		<configuration>
			<compilerArgs>
				<arg>--add-exports</arg>
				<arg>java.base/jdk.internal.ref=ALL-UNNAMED</arg>
				<arg>--add-exports</arg>
				<arg>java.base/sun.nio.ch=ALL-UNNAMED</arg>
				<arg>--add-exports</arg>
				<arg>jdk.unsupported/sun.misc=ALL-UNNAMED</arg>
				<arg>--add-exports</arg>
				<arg>jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED</arg>
				<arg>--add-opens</arg>
				<arg>jdk.compiler/com.sun.tools.javac=ALL-UNNAMED</arg>
				<arg>--add-opens</arg>
				<arg>java.base/java.lang=ALL-UNNAMED</arg>
				<arg>--add-opens</arg>
				<arg>java.base/java.lang.reflect=ALL-UNNAMED</arg>
				<arg>--add-opens</arg>
				<arg>java.base/java.io=ALL-UNNAMED</arg>
				<arg>--add-opens</arg>
				<arg>java.base/java.util=ALL-UNNAMED</arg>
			</compilerArgs>
		</configuration>
	</plugin>
```

and the `JAVA_OPTS` like this:

```
export JAVA_OPTS="$JAVA_OPTS <your java opts here> \
						  --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED \
						  --add-exports=java.base/sun.nio.ch=ALL-UNNAMED \
						  --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED \
						  --add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
						  --add-opens=jdk.compiler/com.sun.tools.javac=ALL-UNNAMED \
						  --add-opens=java.base/java.lang=ALL-UNNAMED \
						  --add-opens=java.base/java.lang.reflect=ALL-UNNAMED \
						  --add-opens=java.base/java.io=ALL-UNNAMED \
						  --add-opens=java.base/java.util=ALL-UNNAMED"
```

This works with Java 17 Corretto and it's deployed in AWS

**Comment by shanhashcah** [comment]
@esanchezros  Thank you for your support. My project is on spring boot 3.0.1 which is based on maven. So let me try and I'll update you.

Thanks

**Comment by emskaplann** [comment]
@esanchezros I tried running with your jvm args, but still doesn't work:

`java.lang.reflect.InaccessibleObjectException: Unable to make private static native int sun.nio.ch.FileChannelImpl.unmap0(long,long) accessible: module java.base does not "opens sun.nio.ch" to unnamed module @340f438e`

**Comment by shanhashcah** [comment]
@esanchezros Thanks,  now it is ok. If I'll get any difficulties regarding thin I'll reopen the issue.

**Comment by shanhashcah** [comment]
@esanchezros I had migrated my exchange-core project  to java 17 . It's have been sometime to deployed in AWS server.  Now I am seeing  it takes more memory than earlier(when it was running with java 8). Am I missing  some flag or other ? I have installed oracle java 17 in that AWS server and tomcat 10. 

Please guide me.

**Comment by shanhashcah** [comment]
@mzheravin @esanchezros 

Pls guide about the issue. Am I missing something?

Many Thanks

**Comment by caubenganha** [comment]
> @esanchezros I tried running with your jvm args, but still doesn't work:
> 
> `java.lang.reflect.InaccessibleObjectException: Unable to make private static native int sun.nio.ch.FileChannelImpl.unmap0(long,long) accessible: module java.base does not "opens sun.nio.ch" to unnamed module @340f438e`

please use VMs para as follows, it's worked for me


```
--add-exports=java.base/jdk.internal.ref=ALL-UNNAMED
--add-exports=java.base/sun.nio.ch=ALL-UNNAMED
--add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED
--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED
--add-opens=jdk.compiler/com.sun.tools.javac=ALL-UNNAMED
--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED
--add-opens=java.base/java.lang=ALL-UNNAMED
--add-opens=java.base/java.lang.reflect=ALL-UNNAMED
--add-opens=java.base/java.io=ALL-UNNAMED
--add-opens=java.base/java.util=ALL-UNNAMED
--add-opens
java.base/java.lang=ALL-UNNAMED
--add-opens
java.base/java.nio=ALL-UNNAMED
--add-opens
java.base/sun.nio.ch=ALL-UNNAMED
```
