### ISSUE TITLE
Lombok and maven

### ISSUE THREAD

**Issue by magick93** [mzheravin/exchange-core#17]
Hi

I'm trying to use this project as a maven module in another project, however I'm getting the below error which seems to be related to the Lombok Builder annotation.

I'm compiling exchange-core using `mvn clean install' . 

```
java.lang.Error: Unresolved compilation problems: 
	The type org.openpredict.exchange.core.ExchangeCore$ExchangeCoreBuilder cannot be resolved. It is indirectly referenced from required .class files
	The method builder() from the type ExchangeCore refers to the missing type ExchangeCore$ExchangeCoreBuilder
```

Is there are more correct maven command I should use?

**Comment by mzheravin** [comment]
Hi,
which Lombok version of lombok do you use in your project ?
I've tried to update to 1.18.8 (will merge soon) and it compiles without requiring for other changes.
