### ISSUE TITLE
How to improve the core performance of the transaction

### ISSUE THREAD

**Issue by yanmaipian** [mzheravin/exchange-core#20]
Hi mzheravin, I am a developer of Digital Money Corporation. I saw your open source exchange core project on github. I am very interested. I have a few questions I want to ask you.
Is the order suitable for using TreeMap?
Due to the particularly large order, it may cause TreeMap to maintain its own balance, and a large number of rotations will cause performance degradation.
2.UserProfile I will put it in the ChronicleMap, but I don't know if it works,
3. Is it appropriate to use the Chronicle Queue to replace the missing person?
I hope that you can give some advice. 
Thank you.

**Comment by buiminhhuy** [comment]
Hi mzheravin, 
I have a question about about RingBuffer.
I met an issue when using ExchangeApi.submitCommand(cmd), sometime it seem to me, it is not process the order, auto return in the resultConsumer with the cmd resultCode = New. not call handle RiskEngine.
I want to know why above case sometime happen?

Thanks,
Huy Bui

**Comment by mzheravin** [comment]
> Is the order suitable for using TreeMap?
> Due to the particularly large order, it may cause TreeMap to maintain its own balance, and a large number of rotations will cause performance degradation.

That's true, TreeMap perfrormance is very low. The FastOrderBook implementation uses bitset+hashmap as a faster alternative. Luckily sorted data structure is required only for maintaining price buckets.  Also, each order bucket can contain many orders. So in average performance impact is acceptable.

> 2.UserProfile I will put it in the ChronicleMap, but I don't know if it works,
It is possible, you can benefit from features of ChronicleMap. But It can not compete in perfromance with single threaded hash table that exchange-core uses. 

> 3. Is it appropriate to use the Chronicle Queue to replace the missing person?
Please could you explain in more detail what is your idea? I think Disruptor can be replaced with Chronicle Queue. But I not sure if it will work faster.

**Comment by mzheravin** [comment]
> I have a question about about RingBuffer.
> I met an issue when using ExchangeApi.submitCommand(cmd), sometime it seem to me, the order command is not process, and auto return the resultConsumer with the cmd resultCode = New. not call handle RiskEngine.
> I want to know why above case sometime happen? has any wrong on RingBuffer size or Disruptor?

Which command type is it? Maybe you can share a test that reproduces that? Does ringbuffer and speed affects that behavior?
RingBuffer size is validated by Disruptor (2^N), so it should not make any problem.
Handling each message is guaranteed by Disruptor framework, never observerd issues with that. So can be only by logic.
Some message types skiped by hold part of risk engine (cancel, move), but should be handle by matching engine, so can not stay in the new state.
Did you check other fields if they are the same as you expected? Maybe you keep reading command placeholder from outside of the results handler, so api writer publishes next command into it after ring buffer did full turnover?

**Comment by buiminhhuy** [comment]
Hi @mzheravin,
Currently, I do not see this issue more. I run your exchange-core in my product. Sometime, I got the issue in runtime mode, So I am difficult to reproduce this case. Thanks your help.
