### ISSUE TITLE
Add more order types

### ISSUE THREAD

**Issue by azpublic** [mzheravin/exchange-core#22]
Hi! I find your project very interesting. 
Is there any plan to support more order types such as stop market or stop limit orders... or maybe iceberg ... conditional orders ... etc ... 

Is it possible with your structure while keeping performance ? 

Thanks

**Comment by mzheravin** [comment]
Hi,
As far as I know even stop orders are usually implemented not in the exchange core, but at the broker level. If exchange provides end-user functionality (like cryptocurrency exchanges), this can be implemented at the trading gateway level (planning to do so). I think traders who prefer to use complex orders usually ok to sacrifice latency a bit.
So yes I pretty sure extra order types would impact on the performance and latency, except iceberg probably.
