### ISSUE TITLE
Adapte it with websockets, updating balances etc.

### ISSUE THREAD

**Issue by bcashier** [mzheravin/exchange-core#26]
Hi

It's awesome that your project can process 5M orders per seconds !

But in case we can adopte it like this:
- Receive new orders from apache KAFKA (Kafka can handle up to 1M messages per second)
- Send WebSockets to users in order to change browser data like: Orderbook, Latest price, Trade history etc ... (Performances depend on the number of subscribed users and topics, In my case, I am thinking to use RabbitMQ that can handle 1M requests per seconds aswell, and for each order, we can send more than 5 messages: For Seller and Buyer to show updated balance, trade history, orderbook etc...)
- Update users balances inside NoSQL in memory database like REDIS, and balance is updated each time the order of specific user is updated.

WIth all this, we can say that the number of processed orders will be decreased by more than 5x times.

Can it be customized with this features ? DO you have better approach for better performances ?

Thanks in advance :)

**Comment by dineralex** [comment]
I think you missing the concept of core :)
Wrap it with your ecosystem and do whatever you need for your project.
The core itself is awesome!

**Comment by mzheravin** [comment]
Dear @bcashier,
If everything you mentioned is running on the same machine - yes, platform throughput will much lower.
However echange-core is designed for multi-node processing, where different clients can be sharded between multiple servers, where you can use any tachnology like Kafka, Redis, RabbitMQ. Exchange-core is only bottleneck, - place where trading operations between arbitrary clients are processed - this is why performance is critical and functionality is stricted.

**Comment by bcashier** [comment]
@mzheravin Thank you for your answer !

But how user balances, trade history updated in the database ? exchange-core must be in connection with the database or another node that is in charge to update it no ?

exchange-core must send logs to the another node (sending datas like user balance, orders, trade history etc.), how it is managed using your project ?

Thanks again and sorry to annoye you with this again !

**Comment by mzheravin** [comment]
Yes, exchange-core is a source of truth for balances and trades. 
It should have external connection with database, to store symbols metadata, trades history, ticks, accunts - everything you need to access independently. 
Synchronization between core and database is done by processing incoming commands and outgoing events (results).

**Comment by vahidalvandi** [comment]
do exchange core can work with kafka ?
