### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by HeliasEurodyn** [mzheravin/exchange-core#27]
Could you provide a simple example on the usage of the library.
Just create a 2-3 users
add some bids
get the order book list
get the matches of the bids

I just build it and try to use it on an app, it is not so clear how to do those steps. 

Thank you.

**Comment by pscanlon1** [comment]
I would check out this file, its more than what you are asking for, but its a good place to start. Combine that with your favorite IDE/Debugger, and you are good to go.

https://github.com/mzheravin/exchange-core/blob/master/src/test/java/exchange/core2/tests/util/ExchangeTestContainer.java

**Comment by mzheravin** [comment]
Hi, 
Please have a look into recent README.md
It has usage example.
