### ISSUE TITLE
How to ensure the accuracy of the data(account / order / balance ) when saving the snapshot? E.g. transaction

### ISSUE THREAD

**Issue by JoyJava** [mzheravin/exchange-core#34]
Now we have a question: how to ensure the accuracy of the data(account / order / balance ) when saving the snapshot? 
E.g. transaction

**Comment by mzheravin** [comment]
If you mean checking "consistency" - you can use TotalCurrencyBalanceReport for that (there is an example in tests).
If you mean "precision" - any operation inside the exchange core is performed with using smallest currency unit (cent, satoshi, zsabo, etc). So there is no accuracy loss possible.

**Comment by Janche** [comment]
Ether's maximum precision is 18 bits, long supports up to 19 bits, ETH's integer portion plus the decimal portion is not enough @mzheravin
