### ISSUE TITLE
Fast vs Direct Order Books

### ISSUE THREAD

**Issue by dineralex** [mzheravin/exchange-core#35]
Can you please explain difference between Fast and Direct in terms of Use Cases?

**Comment by mzheravin** [comment]
Generally, "Direct" order book is recommended to use, even though I did not make deep performance testing yet. 
I have noticed that "Fast" order book provide higher throughput for small order book sizes (less than 1000 orders), but for larger order book sizes "Direct" order book gives up to 4x better throughput. 
I expect "Direct" order book will provide much better latency for complicated operations, like big size order matching. Planning to create tests to prove that soon.
Another advantage of "Direct" order book is that it does require much memory for empty order book "Fast" order book has such issue, so it was difficult to scale over few thousands symbols.  
I planning to continue imporving "Direct" order book implemenatation, whereas "Fast" will remain for comparison purposes only.
