### ISSUE TITLE
Ca it handle 1M OrderBooks? :)

### ISSUE THREAD

**Issue by dineralex** [mzheravin/exchange-core#36]

**Comment by mzheravin** [comment]
Well, never tested. Most probably yes, if you have enough RAM. 
Actually 100K order books is a real busines case scenario. Don't know if any exchange has 1M active symbols though.
Currently order books allocation is not very efficient in terms of memory consumption. I would need to introduce shared object pools to fix that.

**Comment by mzheravin** [comment]
I have just runned the test for 1M symbols, and the core can handle them easily.
For example with 3M pending orders and 1M users (3M accounts) at 1M TPS rate mean latency is about 2.5us. "Worst" latency is about 100us, but this is just a synthetic test.

**Comment by dineralex** [comment]
Cool implementation. I will explain where my question come from. The world is in the early stage of assets digitization. Such that, we will face situation where every day new token types (currencies) and as result new symbols will be created. In such situation 1M symbols become a real case.
