### ISSUE TITLE
activeOrderId, activeOrderUid, activeOrderAction removed from MatcherTradeEvent

### ISSUE THREAD

**Issue by dineralex** [mzheravin/exchange-core#39]
Maksim, can you please explain why did you removed activeOrderId, activeOrderUid, activeOrderAction from MatcherTradeEvent?

Because from consuming perspective it's essential information.
As a core consumer I do want to know these details.

**Comment by dineralex** [comment]
I think I got you....

Because it is data duplication and you have it in OrderCommand...

Am I right?

**Comment by mzheravin** [comment]
Exactly. I am trying to reduce memory footprint and increase matching throughput.
