### ISSUE TITLE
What is the difference of the codes about lamx/disruptor between  in the src directory and https://github.com/LMAX-Exchange/disruptor?

### ISSUE THREAD

**Issue by aihua** [mzheravin/exchange-core#4]
What is the difference of the codes about lamx/disruptor between  in the src directory and https://github.com/LMAX-Exchange/disruptor? Why not using lamx/disruptor via maven or gradle:

<dependency>
  <groupId>com.lmax</groupId>
  <artifactId>disruptor</artifactId>
  <version>3.4.2</version>
</dependency>

or 

implementation 'com.lmax:disruptor:3.4.2'

@mzheravin

**Comment by mzheravin** [comment]
Good question.
For this project I need limited-cycles wait strategies and thread affinity.

**Comment by mballoni** [comment]
So, this means that you replicates LMAX code to change a few parts of it?

**Comment by aihua** [comment]
Then, What is the version of LMAX code used? Why not using inheritance to override some method of class? Thus, we will not maintain the LMAX code used, only using it via maven or gradle.  @mzheravin

**Comment by mzheravin** [comment]
> So, this means that you replicates LMAX code to change a few parts of it?
True. But those are very important changes.

> Then, What is the version of LMAX code used? Why not using inheritance to override some method of class? Thus, we will not maintain the LMAX code used, only using it via maven or gradle. @mzheravin
I pretty sure the version was 3.4.1 at the moment. This is good point, but inheritance is not applies there, these are core classes not extendable. Though, I have plans to handle this with disruptor developers to get rid of cloned source code in the project.

**Comment by aihua** [comment]
Well, then pull a request to https://github.com/LMAX-Exchange/disruptor and merge by the maintainer of the LMAX disruptor code is an idea. @mzheravin

**Comment by scottjbarr** [comment]
Upstream is now at 3.4.2. 

I would be keen to contribute a PR to help bring the code up to date with upstream to minimise the differences, but before that I would like to see some updates on #1 .

**Comment by mzheravin** [comment]
@scottjbarr Yes, I'm currently doing the work in the 006-rapidoid branch in order to facilitate these issues. Basically, now application starts and there is an REST endpoint letting you perform some basic operations synchronously.
What regards to getting rid of disruptor code - I think I found a possibility to construct what I need without having a source code. Just need some more time for experiments.
