### ISSUE TITLE
Risk engine and balances as optional feature

### ISSUE THREAD

**Issue by dineralex** [mzheravin/exchange-core#40]
It is possible to make risk engine as optional feature? Does it make sense from your perspective?
I'm trying to use your engine in distributed ledger environment.(Work like a charm, by the way) . The issue is that balances synchronization is very costly task. The idea is to use "smart contract" as a risk engine on upper layer, because balance on ledger is actual single source of truth.
What do you think? Please advice.

**Comment by mzheravin** [comment]
The idea of the Exchange Core to provide strong consistency and deterministic execution guarantees keeping with highest theoretical possible performance and resilence. Risk Engine design is focused on this. 
As far as i understand disributed ledger reaches resilancy through different techiques. Without the Risk Engine maybe it is more reasonable to build something over on IOrderBook.
From my side maybe it would nice to provide some convenient API to build solutions with existing order books implementations.

**Comment by dineralex** [comment]
Got it and totally agree with your state of mind. The reason for this question is that I don't like to use internal library implementations from encapsulation perspective. I will investigate IOrderBook creations and life-cycle. Will appreciate if you will think about kind of "LEGO" style API for this kind of usage. Thanks in advance!

**Comment by mzheravin** [comment]
Hello,
Risk engine can be disabled through configuration since version 0.5.0
In futher releases I will optimize entire processing flow, to reduce overhead from inactive components.

**Comment by dineralex** [comment]
Hi Maxim, thanks! Will check latest version.
