### ISSUE TITLE
can i matching order with myself?

### ISSUE THREAD

**Issue by Narsiss** [mzheravin/exchange-core#43]
I tried the tests ITExchangeCoreIntegration.basicFullCycleTestExchange with a same uid(UID_1).
I want to matching my orders by myself, but get a lot of asserts.

**Comment by mzheravin** [comment]
Yes. There is a plan to change current orders matching behavior to the one you are expecting. Very soon, vecause it blocks me from creating faster matching algorithm.

**Comment by mzheravin** [comment]
Hello. Matching of orders having same uid (owner) is enabled since version 0.5.0
