### ISSUE TITLE
Abstract the matching engine 

### ISSUE THREAD

**Issue by rohinrohin** [mzheravin/exchange-core#50]
I have a use case where user/balance/execute order systems are already built and I'm looking to only hook into a new order matching engine. 

On this regard I have two questions: 
1. Can I abstract user and other services from this code to only work at the buy/sell order level. Output should be transactions to execute. 
2. Does this engine support 1:M matching? If there was 1 user selling 1BTC for USD and 3 users buying 0.3 BTC from USD. 

Thanks and any help is greatly appreciated :) 
Rohin Gopalakrishnan

**Comment by mzheravin** [comment]
Hello,
1. Currently it is difficult to do, But such is a new feature I going to add soon where you can disable risk control completely.
2. Yes of caurse.

**Comment by mzheravin** [comment]
Hello
With the new feature you can disable risk control completely. 
OrdersProcessingConfiguration.NO_RISK_PROCESSING
Awailable since 0.5.0
