### ISSUE TITLE
Can not access Disruptor internals when starting the project

### ISSUE THREAD

**Issue by lannuo** [mzheravin/exchange-core#55]
Hi Maksim, I hava a question about the core. We are using your core as a dependency. But when starting the project throw a exception " Can not access Disruptor internals" .

**Comment by lannuo** [comment]
final Field f = getField(BlockingWaitStrategy.class, "mutex");

Hi Maksim, how do you think replace "mutex"  to "processorNotifyCondition" ?

**Comment by lannuo** [comment]
and replace 
synchronized (mutex) {
                    sequenceBarrier.checkAlert();
                    mutex.wait();
 }
with 
sequenceBarrier.checkAlert();
mutex.wait();

**Comment by mzheravin** [comment]
Hi @lannuo yes this is a known bug in the last commit. 
Will be resolved very soon.
Disruptor uses older blocking mechanism in the last release, not "mutex"-  I forgot about that so now exchange core fails.

**Comment by mathsCode** [comment]
This issue is fixed for mine, many thanks.
