### ISSUE TITLE
exchange-core source code

### ISSUE THREAD

**Issue by shanhashcah** [mzheravin/exchange-core#60]
I have imported source code into eclipse but it showing error at code level like " The method builder() is undefined for the type ApiPlaceOrder","The constructor StateHashReportResult(new TreeMap<>()) is undefined". So how do compile and rune the code.

Thanks

**Comment by mzheravin** [comment]
Hi
Most probably you need to install lombok plugin and enable annotations processong during the compile time.

**Comment by shanhashcah** [comment]
Thanks. I already did this. Initially I could not understand it.
