### ISSUE TITLE
Recovering users balances and orderbook in case of crash ?

### ISSUE THREAD

**Issue by bcashier** [mzheravin/exchange-core#61]
Hi,

Does it have a system to recover users balances, orderbook etc. in case the matching engine crash because of server shutdown and another factors ?

Thank you !

**Comment by mzheravin** [comment]
Hi,
yes everything recovered from last snapshot + journal

**Comment by bcashier** [comment]
@mzheravin Thanks for your answer !

So they are saved in dumps folder inside files ?

**Comment by mzheravin** [comment]
Yes. Orders in orderbooks, accounts and positions actually is major part of those files. 
But it journalling still under develpment and has some issues (#59)

**Comment by bcashier** [comment]
I see ! Thank you for this infos.
