### ISSUE TITLE
Can you write a simple description of the system？

### ISSUE THREAD

**Issue by cocoyes** [mzheravin/exchange-core#62]
Hello, I'm also a java engineer. I'm really happy to find a matchmaking system. Thank you very much for your contribution! Can you explain the operation principle of the system, such as how to ensure the data security when the system crashes, can you explain it briefly? Thank you very much

**Comment by mzheravin** [comment]
Hello,
Thanks for the interest.
Yes, I'm working on the documentation.
One of the solutions - system state is recovered from snapshot and subsequent records from the journal.
Another option is to use external storage (database) to track state of the orders and accounts, so just need to load them into the exchange core during startup (it is also quite fast).

**Comment by cocoyes** [comment]
> ders and accounts, so just need to load them into the exchange core during startup (it is also quite fast).

thanks,
