### ISSUE TITLE
exchange-core orderbook

### ISSUE THREAD

**Issue by shanhashcah** [mzheravin/exchange-core#64]
In exchange-core project, where orders are store? If I keep the order inside a database then what should I do?

Thanks

**Comment by mzheravin** [comment]
@shanhashcah orders are stored in-memory. You just need to process outgoing events from exchange-core with you custom handler and update orders accordingly (they can be matched, cancelled, etc)

**Comment by shanhashcah** [comment]
Thanks @mzheravin , I understood.
Here orders are stored inside map. Now if project will stopped then how would I recover all orders which are placed before?

**Comment by mzheravin** [comment]
One option you turn journalling on and recover from it. 
Another option you write orders into database, and after reastart you just read all pending orders on insert them into exchnage-core.

**Comment by shanhashcah** [comment]
Thanks @mzheravin .
In exchange-core project how can I turn on journal option. Actually I have looked into the project but did not get any journal option.

**Comment by rhzx3519** [comment]
> Thanks @mzheravin .
> In exchange-core project how can I turn on journal option. Actually I have looked into the project but did not get any journal option.

It's in `SerializationConfiguration` class, you can turn on the journal option by setting the class variable `enableJournaling = true`.

**Comment by shanhashcah** [comment]
Thanks @rhzx3519 

I have enabled Journal option for DISK_JOURNALING and .ecj file is created inside the  dumps folder of exchange-core project. 

So this file contain all orders, users whatever I put during runtime? If I need to get data back from the file i.e existing orders,users etc then what should I do?

Thanks

**Comment by rhzx3519** [comment]
@shanhashcah you can find function `void startup()` in class `ExchangeCore`. when `ExchangeCore` initialized, it will use `serializationProcessor.replayJournalFullAndThenEnableJouraling` read data from journaling which are persisted to .ecj file before,  and publish all commands into RingBuffer. 

So you just restart your program and you should see all orders, users, etc in memory.

**Comment by shanhashcah** [comment]
Thanks @rhzx3519 

Sorry delay in response.
