### ISSUE TITLE
exchange-core Trade details

### ISSUE THREAD

**Issue by shanhashcah** [mzheravin/exchange-core#65]
In exchange-core project, how do I get trade details and trade price( which price offer get matched). 

Thanks

**Comment by mzheravin** [comment]
Hello,
Matched (maker) price is available here: 

https://github.com/mzheravin/exchange-core/blob/2a852909071dc1ae1c04b2f67bd069214d17b545/src/main/java/exchange/core2/core/IEventsHandler.java#L84

Please note that it can be either offer or bid price, it depends.

**Comment by shanhashcah** [comment]
Thanks @mzheravin  I got it.
