### ISSUE TITLE
MatchingEngineRouter only support one symbol now?

### ISSUE THREAD

**Issue by theone-pang** [mzheravin/exchange-core#7]
MatchingEngineRouter only support one symbol now?

**Comment by mzheravin** [comment]
Related logic was recently improved, please checkout current master branch.
Different symbol orderbooks are stored in the hashtable:
`IntObjectHashMap<IOrderBook> orderBooks`
and populated with series of BINARY_DATA messages. This makes symbol to be activated atomically.
