### ISSUE TITLE
Question about putting journaling module in the event handlers?

### ISSUE THREAD

**Issue by rhzx3519** [mzheravin/exchange-core#70]
Hi@mzheravin,
As I can see in the source code, the journaling module is served as an event handler.
All event handlers are executed in order, do you even consider IO operations in the journaling module would
slow down the performance of the whole system.

Is it better to pull the journaling module out of the event handler group and to do the persisting operations before publishing events to ringbuffer.

**Comment by mzheravin** [comment]
Hi @rhzx3519 
Yes disk journaling module IO is slowing down whole core, total latency will be about 50us-200us (depending on hardware and traffic).
By default, initializer does not attaching jounraling event handler and does not put extra sequence barrier for it. Theese are only added if jounraling is turned on. 
The idea is that, accouring to some regulations, exchange should not return to the client anything that was not written into journal (meaning of that can vary). If there is no such requirement, then journal writing can be initiated at any point and we dont care much when it is finished.

**Comment by rhzx3519** [comment]
@mzheravin Thanks for your answer!
