### ISSUE TITLE
Concurrency Issue 

### ISSUE THREAD

**Issue by shanhashcah** [mzheravin/exchange-core#72]
In multi-threaded environment, getting java.util.ConcurrentException in OrderBucketNative class for below line.
final Map.Entry<Long, Order> next = iterator.next(); 

In this class LinkedhashMap is being used to collect and remove all matching orders. So can I use any Concurrent Collection instead to avoid ConcurrentException.

Thanks

**Comment by mzheravin** [comment]
Orderbooks (and OrderBucketNative in particular) implementation is strictly single threaded. 
Using concurrent collections can not guarantee thread safety, beacuse whole order book does not ready to keep internal consistency under direct multithreaded access.

**Comment by shanhashcah** [comment]
Thanks @mzheravin 

Is there any way to run exchange-core in multi-threaded environment?

**Comment by mzheravin** [comment]
exchange-core is working in multi-threaded environment (4+ threads).

**Comment by shanhashcah** [comment]
ok Thanks @mzheravin
