### ISSUE TITLE
OrderBook Creation

### ISSUE THREAD

**Issue by shanhashcah** [mzheravin/exchange-core#79]
As exchange-core has single symbol supported orderbook i.e one orderbook contains one symbol. So if we have multiple symbol lets say 50 or 100 symbol then 50 or 100 orderbooks will be created. In code level I need to create multiple OrderBookNativeImpl object. So is there any way to minimize this object(OrderBookNativeImpl) object creation.

Thanks

**Comment by mzheravin** [comment]
Sorry but I'm not sure I understand what is wrong with creating independent OrderBook per each Symbol.
Any particular order book referring to specific symbol having specific bids and offers. There is one-to-one connection.
OrderBook is a lightweight object and you can have over 200'000 orderbooks (the only limitation is a JVM heap size), which is sufficient for any exchange.

**Comment by shanhashcah** [comment]
Thanks @mzheravin , sorry about to delay in my respond.

In exchange-core project orderid/offerid  data type is long, so in real time there may be lengthy orderid/offerid So in that case may we get some issue?

**Comment by shanhashcah** [comment]
Thanks @mzheravin  I understood!!
