### ISSUE TITLE
OrderId datatype

### ISSUE THREAD

**Issue by shanhashcah** [mzheravin/exchange-core#80]
In exchange-core project orderid/offerid data type is long, so in real time there may be lengthy orderid/offerid So in that case may we get some issue?

**Comment by mzheravin** [comment]
Please could you explain with the example?
OrderId has long datatype everywhere so you can use any value from LONG_MIN to LONG_MAX.
With 1M TPS you would need almost 300 years to saturate long.

**Comment by shanhashcah** [comment]
Thanks @mzheravin 
Actually I mean to say  orderid is an incremental type, so in real time application there are huge transactions and orderid also get incremented. Say for example , right now orderid is 3536396  and it is incremental . That is why I am confused that  after incremented over time may  orderid value go beyond the LONG_MAX? I am not sure about that. Please help.

**Comment by mzheravin** [comment]
Yes, my point is when you notice it goes close to the LONG_MAX you will have plenty of time to rewrite everything to 128-bit counters, and this will be very minor problem. 
For example to store orders history, you would need over 1 billion terabytes.

**Comment by shanhashcah** [comment]
Thanks @mzheravin 
In production environment I need to generate unique orderid and place an offer. In that case when orderid close to the LONG_MAX or beyond LONG_MAX , how would I generate unique orderid after that limit/LONG_MAX. In production environment I can not reuse an orderid which already generated.

**Comment by shanhashcah** [comment]
Hi:
@mzheravin 

Can you please give me any suggestion for my above concern. 

Thanks in advance.

**Comment by mzheravin** [comment]
LONG_MAX (2^63) is a very high limit, it is enough to count all trades ever happend on the Earth between two individuals. I dont see any problem here. Disruptor has the same assumption btw, it will break after 300 years if your system handles 1M messages per second and never got restarted. Morover, most databases have the same limit for PK (if it is BIGINT column), so we can ask them :)

**Comment by shanhashcah** [comment]
Thanks @mzheravin  for your support. If I get any issue on this I will get back to you.
