### ISSUE TITLE
Maximum capacity of keeping orders

### ISSUE THREAD

**Issue by shanhashcah** [mzheravin/exchange-core#90]
Hi @mzheravin 

In exchange-core what is the maximum limit to hold total number of offers. I mean how many total offers exchange core can obtain?

Thank You..

**Comment by mzheravin** [comment]
Hi @shanhashcah
Limit is 2^31 orders in each orderbook. 
It is possible to create up to 2^31 orderbooks - that gives 2^62 orders theoretical limit.

**Comment by shanhashcah** [comment]
Okay Thank U @mzheravin 
As per my understanding we can have around 2.1 billon orderbook and around four quintillion total orders.

Correct me Sir if I am calculating wrong.
